#include <string>
using namespace std;


// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.

char findTheDifference(string, string);


char findTheDifference(string s, string t)
{
    string returnString = t;
    for (int charIndex = 0; charIndex < s.length(); charIndex++)
    {
        int eraseIndex = returnString.find_first_of(s[charIndex]);
        returnString.erase(returnString.begin() + eraseIndex);
    }
    return returnString[0];
}